var mouseOffset=null;var iMouseDown=false;var lMouseState=false;var dragObject=null;var DragDrops=[];var curTarget=null;var lastTarget=null;var dragHelper=null;var tempDiv=null;var rootParent=null;var rootSibling=null;var graph_height=14;Number.prototype.NaN0=function(){return isNaN(this)?0:this;}
function CreateDragContainer(){var cDrag=DragDrops.length;DragDrops[cDrag]=[];for(var i=0;i<arguments.length;i++){var cObj=arguments[i];DragDrops[cDrag].push(cObj);cObj.setAttribute('DropObj',cDrag);for(var j=0;j<cObj.childNodes.length;j++){if(cObj.childNodes[j].nodeName=='#text')continue;cObj.childNodes[j].setAttribute('DragObj',cDrag);}}}
function getPosition(e){var left=0;var top=0;while(e.offsetParent){left+=e.offsetLeft+(e.currentStyle?(parseInt(e.currentStyle.borderLeftWidth)).NaN0():0);top+=e.offsetTop+(e.currentStyle?(parseInt(e.currentStyle.borderTopWidth)).NaN0():0);e=e.offsetParent;}
left+=e.offsetLeft+(e.currentStyle?(parseInt(e.currentStyle.borderLeftWidth)).NaN0():0);top+=e.offsetTop+(e.currentStyle?(parseInt(e.currentStyle.borderTopWidth)).NaN0():0);return{x:left,y:top};}
function mouseCoords(ev){if(ev.pageX||ev.pageY){return{x:ev.pageX,y:ev.pageY};}
return{x:ev.clientX+document.body.scrollLeft-document.body.clientLeft,y:ev.clientY+document.body.scrollTop-document.body.clientTop};}
function getMouseOffset(target,ev){ev=ev||window.event;var docPos=getPosition(target);var mousePos=mouseCoords(ev);return{x:mousePos.x-docPos.x,y:mousePos.y-docPos.y};}
function mouseMove(ev){ev=ev||window.event;var target=ev.target||ev.srcElement;var mousePos=mouseCoords(ev);if(lastTarget&&(target!==lastTarget)){var origClass=lastTarget.getAttribute('origClass');if(origClass)lastTarget.className=origClass;}
var dragObj=target.getAttribute('DragObj');if(dragObj!=null){if(target!=lastTarget){var oClass=target.getAttribute('overClass');if(oClass){target.setAttribute('origClass',target.className);target.className=oClass;}}
if(iMouseDown&&!lMouseState){curTarget=target;rootParent=curTarget.parentNode;rootSibling=curTarget.nextSibling;mouseOffset=getMouseOffset(target,ev);for(var i=0;i<dragHelper.childNodes.length;i++)dragHelper.removeChild(dragHelper.childNodes[i]);dragHelper.appendChild(curTarget.cloneNode(true));dragHelper.style.display='block';var dragClass=curTarget.getAttribute('dragClass');if(dragClass){dragHelper.firstChild.className=dragClass;}
dragHelper.firstChild.removeAttribute('DragObj');var dragConts=DragDrops[dragObj];curTarget.setAttribute('startWidth',parseInt(curTarget.offsetWidth));curTarget.setAttribute('startHeight',parseInt(curTarget.offsetHeight));curTarget.style.display='none';for(var i=0;i<dragConts.length;i++){with(dragConts[i]){var pos=getPosition(dragConts[i]);setAttribute('startWidth',parseInt(offsetWidth));setAttribute('startHeight',parseInt(offsetHeight));setAttribute('startLeft',pos.x);setAttribute('startTop',pos.y);}
for(var j=0;j<dragConts[i].childNodes.length;j++){with(dragConts[i].childNodes[j]){if((nodeName=='#text')||(dragConts[i].childNodes[j]==curTarget))continue;var pos=getPosition(dragConts[i].childNodes[j]);setAttribute('startWidth',parseInt(offsetWidth));setAttribute('startHeight',parseInt(offsetHeight));setAttribute('startLeft',pos.x);setAttribute('startTop',pos.y);}}}}}
if(curTarget){dragHelper.style.top=mousePos.y-mouseOffset.y;dragHelper.style.left=mousePos.x-mouseOffset.x;var dragConts=DragDrops[curTarget.getAttribute('DragObj')];var activeCont=null;var xPos=mousePos.x-mouseOffset.x+(parseInt(curTarget.getAttribute('startWidth'))/2);var yPos=mousePos.y-mouseOffset.y+(parseInt(curTarget.getAttribute('startHeight'))/2);for(var i=0;i<dragConts.length;i++){with(dragConts[i]){if((parseInt(getAttribute('startLeft'))<xPos)&&(parseInt(getAttribute('startTop'))<yPos)&&((parseInt(getAttribute('startLeft'))+parseInt(getAttribute('startWidth')))>xPos)&&((parseInt(getAttribute('startTop'))+parseInt(getAttribute('startHeight')))>yPos)){activeCont=dragConts[i];break;}}}
if(activeCont){var beforeNode=null;for(var i=activeCont.childNodes.length-1;i>=0;i--){with(activeCont.childNodes[i]){if(nodeName=='#text')continue;if(curTarget!=activeCont.childNodes[i]&&((parseInt(getAttribute('startLeft'))+parseInt(getAttribute('startWidth')))>xPos)&&((parseInt(getAttribute('startTop'))+parseInt(getAttribute('startHeight')))>yPos)){beforeNode=activeCont.childNodes[i];}}}
if(beforeNode){if(beforeNode!=curTarget.nextSibling){activeCont.insertBefore(curTarget,beforeNode);}}else{if((curTarget.nextSibling)||(curTarget.parentNode!=activeCont)){activeCont.appendChild(curTarget);}}
setTimeout(function(){var contPos=getPosition(activeCont);activeCont.setAttribute('startWidth',parseInt(activeCont.offsetWidth));activeCont.setAttribute('startHeight',parseInt(activeCont.offsetHeight));activeCont.setAttribute('startLeft',contPos.x);activeCont.setAttribute('startTop',contPos.y);},5);if(curTarget.style.display!=''){curTarget.style.display='';curTarget.style.visibility='hidden';}}else{if(curTarget.style.display!='none'){curTarget.style.display='none';}}}
lMouseState=iMouseDown;lastTarget=target;if(dragObject){dragObject.style.position='absolute';dragObject.style.top=mousePos.y-mouseOffset.y;dragObject.style.left=mousePos.x-mouseOffset.x;}
lMouseState=iMouseDown;if(curTarget||dragObject)return false;}
function mouseUp(ev){if(curTarget){dragHelper.style.display='none';if(curTarget.style.display=='none'){if(rootSibling){rootParent.insertBefore(curTarget,rootSibling);}else{rootParent.appendChild(curTarget);}}
curTarget.style.display='';curTarget.style.visibility='visible';}
curTarget=null;dragObject=null;iMouseDown=false;}
function mouseDown(ev){ev=ev||window.event;var target=ev.target||ev.srcElement;iMouseDown=true;if(target.onmousedown||target.getAttribute('DragObj')){return false;}}
document.onmousemove=mouseMove;document.onmousedown=mouseDown;document.onmouseup=mouseUp;window.onload=function(){var row_container_index=1;var row_container=document.getElementById('draggable_row_container_'+row_container_index);while(row_container!=null){CreateDragContainer(row_container);row_container_index++;row_container=document.getElementById('draggable_row_container_'+row_container_index);}
dragHelper=document.createElement('DIV');dragHelper.style.cssText='position:absolute;display:none;';document.body.appendChild(dragHelper);}
function buildPatchPositions(){var patch_positions="";var child_node,sub_child_node;var draggable_container;var row_container_index=1;var row_container=document.getElementById('row_container_'+row_container_index);while(row_container!=null){for(var i=0;i<row_container.childNodes.length;i++){child_node=row_container.childNodes[i];if(child_node.nodeName=='#text')continue;if(child_node.id.indexOf('patch')==0){patch_positions+=getPositionFromPatchId(child_node.id)+',';}
else{for(var j=0;j<child_node.childNodes.length;j++){sub_child_node=child_node.childNodes[j];if(sub_child_node.nodeName=='#text')continue;if(sub_child_node.id.indexOf('patch')==0){patch_positions+=getPositionFromPatchId(sub_child_node.id)+',';}}}}
row_container_index++;row_container=document.getElementById('row_container_'+row_container_index);}
patch_positions=patch_positions.substring(0,patch_positions.lastIndexOf(','))
document.getElementById('patch_positions').setAttribute('value',patch_positions);return true;}
function getPositionFromPatchId(patch_id){return patch_id.substring(patch_id.lastIndexOf('_')+1,patch_id.length)}